### ISSUE TITLE
Concertar possivel bug PGS

### ISSUE THREAD

**Issue by jr9Hernandez** [rubensolv/GAforMicroRTSCluster#15]
Aparentemente o PGS está jogando a partida toda com o ultimo script do portfolio.

**Comment by rubensolv** [comment]
Analisando ações do PGS. 
Executado um teste entre o PGS com o portfólio contendo o LR e RR (nesta ordem) e as ações selecionadas para as unidades mudam em cada escolha.
Segue , abaixo, fragmento das tomadas de ação:
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   LightRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (22,22), 1, 1)   LightRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   LightRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (21,22), 1, 1)   LightRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   LightRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (21,22), 1, 0)   LightRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   LightRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (22,22), 1, 0)   LightRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   RangedRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (22,22), 1, 0)   RangedRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   RangedRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (22,22), 1, 1)   RangedRush(AStarPathFinding)
Player for computation= 1
Unit   ---->  Script 
Barracks(88081)(1, (22,21), 4, 0)   LightRush(AStarPathFinding)
Base(21)(1, (21,21), 10, 0)   RangedRush(AStarPathFinding)
Worker(26)(1, (21,22), 1, 1)   LightRush(AStarPathFinding)

**Comment by rubensolv** [comment]
Em uma análise posterior foi identificado que a tendência do PGS utilizando os scripts padrão (WR, LR, RR e HR) vão seguir, em geral, o comportamento do primeiro scritp que existir no portfólio.
Porém foi encontrado caso perfeito que mostra a capacidade de mixar scripts do portfólio.
Segue link, em anexo, para visualização do comportamento:
https://drive.google.com/open?id=1ns_FBIQW6q72-wm9t2pHdjHS14zVIQ7p

Pelo vídeo fica claro que o PGS escolhe o primeiro script do portfolio, que consiste de {RR, LR , HR}, para iniciar o processo tendo em vista que eles, neste momento, apontam o mesmo ganho de valores para a função de avaliação.
Porém conforme o inimigo (LR) apresenta vitória sob as unidades RR o PGS muda as escolhas das unidades produzidas.

**Comment by rubensolv** [comment]
Identificado o problema.
No PGS o método getFinalAction utiliza o nome da IA (String) que deve ser único, para fazer a transcrição das ações. 
Para correção do problema penso em fazer com que a classe BasicExpandedConfigurableScript possa imprimir os valores dos choices para mostrar a diferença entre os scripts. 
Verificando possibilidade.

**Comment by rubensolv** [comment]
Mudanças no método toString da classe BasicExpandedConfigurableScript para que possa ser usado no PGS. 
O método do PGS (getFinalAction) faz o uso do nome (string) da classe para reduzir o número de consultas aos scripts.
Com base nisso o método toString das IA's utilizadas no portfólio precisam ser únicas. 
O toString da classe BasicExpandedConfigurableScript foi reescrito para ser impresso de forma única, imprimindo os choices que são utilizados.
Segue vídeo do novo comportamento utilizando a classe BasicExpandedConfigurableScript:
https://drive.google.com/open?id=1ns_FBIQW6q72-wm9t2pHdjHS14zVIQ7p
Neste vídeo o PGS (vermelho) enfrenta o LR (Azul) utilizando em seu portfolio uma composição dos scripts com id 3, 2 e 1 (nesta ordem).
Acredito que o problema tenha sido sanado. 
Aguardando verificação do Julian para encerrar o ticket.

**Comment by rubensolv** [comment]
Verificado alterações pelo Julian.
Tudo resolvido.
