### ISSUE TITLE
Verificar problemas na execução dos scripts.

### ISSUE THREAD

**Issue by rubensolv** [rubensolv/GAforMicroRTSCluster#6]
O erro:
![image](https://user-images.githubusercontent.com/11337289/34885654-d89a70de-f7a7-11e7-8cc7-a765f28076bc.png)
Está ocorrendo com frequência nos testes iniciais com mapas 24x24. 
De 360 testes cerca de 250 apresentaram este erro.

Seguem dados para tentar reproduzir o problema:
Chromossomos onde os erros foram encontrados: '63;162;6;149;' e '37;70;145;78;'

Os scripts foram testados individualmente porém nenhum erro foi encontrado.
Os Scripts foram testados em dúplas, também não foi identifcado erros.
Apenas o erro foi identificado no momento em que executa-se com o cromossomo contendo 4 scripts.

Para simular o teste:

gerar o jar do mRTS na versão atual e executar a linha de comando:
java -jar microRTS_teste.jar '63;162;6;149;' '37;70;145;78;'

A classe de testes para essa simulação no mRTS é ClusterTesteLeveRoundRobin.

**Comment by jr9Hernandez** [comment]
Concertado! o erro era por causa de procurar uma base inexistente, na hora de criar barracas.
